### ISSUE TITLE
Reduce number of Node dependencies

### ISSUE THREAD

**Issue by Ta180m** [LadueCS/laduecs.github.io#10]
I'm not entirely sure if this is doable or possible, but it'd be great to reduce our number of dependencies.

What we don't want:
```
added 2003 packages, and audited 2004 packages in 50s

84 packages are looking for funding
  run `npm fund` for details

79 vulnerabilities (8 low, 49 moderate, 22 high)
```

**Comment by theVerySharpFlat** [comment]
Steps:

1. Uninstall React
2. Uninstall everything else

**Comment by Ta180m** [comment]
I'm getting a build error after doing that.

**Comment by theVerySharpFlat** [comment]
uninstall node and npm

**Comment by Ta180m** [comment]
`npm: command not found`

**Comment by Ta180m** [comment]
Unironically I would have preferred to write the website with Bootstrap or a static site generator, but it's ultimately up to @spicecat to make that decision.

**Comment by Ta180m** [comment]
An easy dependency to remove is [smooth-scroll](https://github.com/cferdinandi/smooth-scroll), since it's already deprecated anyways.
