### ISSUE TITLE
Add more useful text content

### ISSUE THREAD

**Issue by Ta180m** [LadueCS/laduecs.github.io#24]
Currently, the website looks really good, but there's not much actual text content. Maybe we could add some more about the club itself, meetings, etc

**Comment by Ta180m** [comment]
For the About Us section:
> We're an afterschool club. We do CS. We're from Ladue. AWWW YEAH!

or anything more descriptive than what we have now.

**Comment by notSam25** [comment]
ASSIGN ME!!!!!!!!!!!
