### ISSUE TITLE
Improvements to the Team section

### ISSUE THREAD

**Issue by Ta180m** [LadueCS/laduecs.github.io#33]
"Team" suggests that these people are on some special team (which isn't entirely inaccurate) but it's pretty misleading. Another option could be to add photos and short descriptions of anyone that wants to be on the website. What to do you all think?

**Comment by Ta180m** [comment]
Perhaps we could make clicking on the photos link to the GitHub accounts or personal websites of each person?

**Comment by theVerySharpFlat** [comment]
What's your plan with how their github accounts should be linked?

**Comment by theVerySharpFlat** [comment]
I say we just put the social media/GitHub icon underneath the description. We need more social media platforms to make it good though...

**Comment by Ta180m** [comment]
> @Ta180m What's your plan with how their GitHub accounts should be linked?

With a link when you click on the image.

**Comment by Ta180m** [comment]
> I say we just put the social media/GitHub icon underneath the description. We need more social media platforms to make it good though...

LadueCS isn't on any other social media platforms and we aren't creating social media accounts for LadueCS since that would be utterly useless.

**Comment by theVerySharpFlat** [comment]
Ok, I actually added an icon below the text. Didn't see your comment. Will make the images links
