### ISSUE TITLE
Navbar logo still looks off because of size

### ISSUE THREAD

**Issue by notAkki** [LadueCS/laduecs.github.io#39]

**Comment by Ta180m** [comment]
Yeah, it'd be a lot nicer if the logo was larger, but CSS is just weird sometimes.

**Comment by notSam25** [comment]
OMG ASSIGN ME!

**Comment by Ta180m** [comment]
@notSam25 be careful for what you ask for

**Comment by Ta180m** [comment]
THIS ISSUE IS SO CURSED...

3dc05065339c09e60bd7c564b4f2e25f6957db61 "fixes" this by somehow moving the icon to the right which no one will ever know why. Don't try touching this again or you'll break it even worse next time.
