### ISSUE TITLE
Weeb

### ISSUE THREAD

**Issue by theVerySharpFlat** [LadueCS/laduecs.github.io#47]
Our site looks like a Weeb site! Let's use Weeb instead! What do you guys think?
#computerscience

**Comment by Ta180m** [comment]
@theVerySharpFlat If you want to rewrite the whole thing in Weebly, go ahead. (or even better, rewrite in vanilla HTML/CSS)

**Comment by theVerySharpFlat** [comment]
no. Weebly. You don't write it. You drag it. Get it right buddy.

**Comment by Ta180m** [comment]
Dragging is wRiTiNg WiTh A mOuSe

**Comment by Ta180m** [comment]
Anyways weebly isn't as cursed as this React blasterpiece

**Comment by theVerySharpFlat** [comment]
You will regret your words, foolish mortal.

**Comment by Ta180m** [comment]
If you've ever tried hacking this cursed React codebase, you'll regret it.

**Comment by notSam25** [comment]
React 'works' fine bozo. @Ta180m  clearly you don't appreciate hours of debugging. smh.

**Comment by theVerySharpFlat** [comment]
hours? years

**Comment by Dexyaa** [comment]
weeb.weebly.com
