### ISSUE TITLE
Calendar for meeting dates

### ISSUE THREAD

**Issue by theVerySharpFlat** [LadueCS/laduecs.github.io#49]
I'll do this one. HANDS OFF! You will see results soon.

**Comment by Ta180m** [comment]
Are you implementing it in Weebly /s

**Comment by theVerySharpFlat** [comment]
@Ta180m it would be really nice if the meeting data file was hosted somewhere where I could just run `fetch()` on it. I hate having to download from gdrive and uploading manually.

**Comment by Ta180m** [comment]
@theVerySharpFlat Does the calendar actually work right now? Also can you add a calendar link to the navbar?

**Comment by Ta180m** [comment]
> @Ta180m it would be really nice if the meeting data file was hosted somewhere where I could just run `fetch()` on it. I hate having to download from gdrive and uploading manually.

You could automate it with rclone but that might be annoying too. Where do you think should we host the meeting data?

**Comment by theVerySharpFlat** [comment]
rclone is cool, but what if we just created a new repo for this and then you could edit it with libreoffice or something and push changes. Then I could run fetch('raw.githubusercontent.com/xxx') and get the csv file. We could create a github action that automatically exports it somehow or something.

**Comment by theVerySharpFlat** [comment]
But I don't want to have to spend too much time on it. Anyways, good luck!

**Comment by Ta180m** [comment]
Since it's near the end of the year and the calendar most likely won't change much, how about we just stick with the currently downloaded csv and worry about updating it later?

**Comment by theVerySharpFlat** [comment]
Sounds good. And easy. I like it.

**Comment by theVerySharpFlat** [comment]
@Ta180m This is done

**Comment by theVerySharpFlat** [comment]
ok

**Comment by Ta180m** [comment]
@theVerySharpFlat This is probably asking for too much, but would it be possible to put some kind of visual indicator on the calendar for days with meetings so you don't have to randomly click until you find one?

**Comment by theVerySharpFlat** [comment]
Huh, I'll have to look into the features of `react-calendar`. I think it might have that feature. I'll have to see. 

However, I'm going to probably leave this to next week because the homework is piling up 😄

**Comment by Ta180m** [comment]
Sounds good. I'm pretty busy too, working on Gitea federation and Intro-to-Python.
