### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by theVerySharpFlat** [LadueCS/laduecs.github.io#5]
You guys should use typescript. 

Ts + react = ❤️

**Comment by Ta180m** [comment]
Sure! Can you make a pull request for this?

**Comment by theVerySharpFlat** [comment]
sounds painful. I'll work on it

**Comment by theVerySharpFlat** [comment]
@Ta180m assign me please

**Comment by theVerySharpFlat** [comment]
I've encountered an issue. The issue is that it is rough to convert to typescript because the project is already progressed to the point where I don't know what any of the types are. If I were to create a props struct for every single part of the json structure that is passed in, perhaps that would be feasible, but with the events that get passed in for say, change events on the contact form, I just can't figure out the types.
